### ISSUE TITLE
[FE] 앱 글로벌 UI 스타일링

### ISSUE THREAD

**Issue by junzero741** [Dae-Hwa/baseball#21]
# 개요
앱 전체의 글로벌 UI 스타일링을 잡겠습니다.

# ToDo
- [x] body 위치잡기
- [x] 기타 스타일링

**Comment by GleamingStar** [comment]
assignee 빼주셔도 될 것 같습니다!

**Comment by GleamingStar** [comment]
아 assignee에 제가 같이 들어있길래 남겼던 코멘트에요
구디는 그대로 넣어두셔도 됩니다!
