### ISSUE TITLE
[FE] ScoreBoard

### ISSUE THREAD

**Issue by GleamingStar** [Dae-Hwa/baseball#25]
#7 

### 구조
- Table
 - 행 : awayTeam, homeTeam
 - 열 : 1회 ~ 12회, R(점수)

### 기능
- [x] 상단 MouseEnter시 슬라이드
- [x] 슬라이드시 자기를 제외한 화면 filter:brightness
  - 상위 컴포넌트에서 setDark 함수를 받아와 조작
  - isDark속성으로 이미 LineUp, ScoreBoard 둘 중 한 친구가 나와있는 상태일 땐 반응하지 않도록 조건 추가 필요
- [x] 백엔드에서 주신 데이터를 적절히 파싱할 함수

**Comment by junzero741** [comment]
개인적으로 ScoreBoard 가 맞다고 생각합니다.  Score 와 Board 의 합성어랄까..
