### ISSUE TITLE
[FE] Refactor for 0508 crong review 

### ISSUE THREAD

**Issue by GleamingStar** [Dae-Hwa/baseball#47]
https://github.com/codesquad-members-2021/baseball/pull/3
#### 각자 진행할 리팩토링의 범위 나누기
- app.js 들여쓰기 수정 / 전체 컴포넌트 들여쓰기 tab:2 로 수정
- Oauth 함수명 재명명
- then / catch 대신 async / await 쓰기
  - +try catch 로 에러처리 하기
- styled component는 전부 하단에 선언
- BallCount.jsx 
  - type 조정
  - styled 속 조건문 조정
- useReducer / useContext 적용
  - 먼저 상위 요소에다 context 만들고 둘이 같이쓰기?
  - 둘이 따로 쓰다 나중에 적절히 합치기?
  - 일단 데이터 처리 및 api이용은 useState쓰다가 나중에 하기?
- 애자일 / 백로그 공부

**Comment by junzero741** [comment]
리뷰 링크 찾아가기 귀찮았는데 정리까지...  최곰다
월요일날 같이 검토해봐요 성님!!
